# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Silverminer007/DynamicRegistries/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "dynamicregistries" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version = "${file.jarVersion}" #mandatory
# A display name for the mod
displayName = "Dynamicregistries" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/Silverminer007/MinecraftModsUpdateChecker/master/dynamicregistries.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://modrinth.com/mod/dynamicregistries" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="dynamicregistries.png" #optional
# A text field displayed in the mod UI
credits="Won-Ton, the author of the PR that was the code base of this library" #optional
# A text field displayed in the mod UI
#authors="Love, Cheese and small house plants" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
Dynamic registries is a library mod that allows the creation of new data-pack based registries.
It's **possible** to define elements in code and trough data-packs (even the data-pack in your mod),
but not necessary; you can also create elements only in code **or** in data-packs.
Elements that were defined in code can also be overwritten from data-packs.
Elements must be encoded in JSON.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.dynamicregistries]] #optional
# the modid of the dependency
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[39,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
# Here's another dependency
[[dependencies.dynamicregistries]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
